### ISSUE TITLE
Problem with required system extensions

### ISSUE THREAD

**Issue by smichaelsen** [TYPO3/CmsComposerPackageGenerator#5]
I have a problem loading EXT:gridelements via composer. This is the error I get:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for typo3-ter/gridelements ~3.0 -> satisfiable by typo3-ter/gridelements[3.0.0].
    - typo3-ter/gridelements 3.0.0 requires typo3-ter/version * -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

Gridelements requires the sysext version. But I think system extensions should be ignored by this composer package generator.

**Comment by lars85** [comment]
the composer.json of typo3/cms contains "typo3/cms-version" in the replace section, but not "typo3-ter/version".

Solution:
packages.json Generator has to reference to typo3/cms-version instead of typo3-ter/version in the require sections of the composer configuration of gridelements (same for all system extensions).

Quick fix:
write this into your htdocs/composer.json:
```json
replace: {
    "typo3-ter/version": "*"
}
```

**Comment by smichaelsen** [comment]
Thanks for the quickfix! Works fine :)

**Comment by helhum** [comment]
version was accidentally published to TER, is removed now
